# Generated by Django 2.2.13 on 2020-12-24 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('company_name', models.CharField(error_messages={'unique': 'This field should be unique'}, max_length=255, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField(max_length=500)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('gst_number', models.CharField(default='', max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField(max_length=500)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('gst_number', models.CharField(default='', max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField(max_length=500)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('gst_number', models.CharField(default='', max_length=50, unique=True)),
                ('distributor_retailers', models.ManyToManyField(db_table='distributes', to='mainApp.Retailer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_distributor_price', models.FloatField()),
                ('product_distributor_margin', models.FloatField()),
                ('product_retailer_price', models.FloatField()),
                ('product_retailer_margin', models.FloatField()),
                ('product_mrp', models.FloatField()),
                ('product_tax', models.FloatField()),
                ('product_discount', models.FloatField()),
                ('cg_gst', models.FloatField()),
                ('sg_gst', models.FloatField()),
                ('hsn_code', models.CharField(default='', max_length=50)),
                ('fssai_number', models.CharField(blank=True, max_length=50, null=True)),
                ('product_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='company_distributors',
            field=models.ManyToManyField(db_table='supplies', to='mainApp.Distributor'),
        ),
    ]
