# Generated by Django 2.2.13 on 2020-12-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyproducts',
            old_name='product_tax',
            new_name='total_tax',
        ),
    ]
