# Generated by Django 2.2.13 on 2020-10-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(error_messages={'unique': 'This field should be unique'}, max_length=255, unique=True),
        ),
    ]
