# Generated by Django 2.2.13 on 2020-12-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20201225_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company2',
            fields=[
                ('address', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pincode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Company3',
            fields=[
                ('pincode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Company4',
            fields=[
                ('city', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
    ]
