# Generated by Django 3.0.5 on 2020-11-13 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20201015_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_distributors',
            field=models.ManyToManyField(db_table='supplies', to='mainApp.Distributor'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='distributor_retailers',
            field=models.ManyToManyField(db_table='distributes', to='mainApp.Retailer'),
        ),
        migrations.CreateModel(
            name='CompanyProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_distributor_price', models.FloatField()),
                ('product_mrp', models.FloatField()),
                ('product_tax', models.FloatField()),
                ('product_discount', models.FloatField()),
                ('product_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Company')),
            ],
        ),
    ]
