# Generated by Django 2.2.13 on 2020-12-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20201227_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company1',
            name='company_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
