# Generated by Django 2.2.13 on 2020-12-27 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20201227_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Pincode'),
        ),
        migrations.AlterField(
            model_name='company1',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Address'),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.City'),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='pincode',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
